use_frameworks!

platform :ios, '10.0'

target 'QoobissSDK_Example' do
  pod 'QoobissSDK', :path => '../'

  target 'QoobissSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
