use_frameworks!

platform :ios, '14.0'

target 'QoobissSDK_Example' do
  pod 'lottie-ios'
  pod 'OntraceSDK', :path => '../OntraceSDK.podspec'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
  
  target 'QoobissSDK_Tests' do
    inherit! :search_paths
  end
end
